#!/usr/bin/env bash
# This script nginx to listen at port 8080
sudo service nginx stop
sed -i 's/^user .*/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/^listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
sudo service nginx start

